### ISSUE TITLE
Add support for Visual Studio 2013

### ISSUE THREAD

**Issue by felixSchl** [mrdooz/TabGroupJumper#2]
What would be involved in making this happen?

**Comment by mrdooz** [comment]
I've updated the versions filed in the .AddIn file now so the addon should work with any Visual Studio version. I read that using the .AddIn files for making plugins is deprecated with Visual Studio 2013, but it still works, and hopefully it won't be broken in 2015.

**Comment by mrdooz** [comment]
Closing issue as resolved.
